### ISSUE TITLE
crash when try upload

### ISSUE THREAD

**Issue by carlosmaid** [Gwindalmir/SEWorkshopTool#13]
this will work fine before the last update (01_186)

D:\Steam\steamapps\common\SpaceEngineers>SEWorkshopTool.exe --upload --mods "C:\Users\Carlos\AppData\Roaming\SpaceEngineers\Mods\Space Latino modulo 2 v4 TEST"
2018-07-23 21:00:22.345: An exception occurred intializing game libraries: Could not load type 'VRage.Steam.MySteamRemoteStorage' from assembly 'VRage.Steam, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nu
ll'.
2018-07-23 21:00:22.348:    at Phoenix.WorkshopTool.MySteamService..ctor(Boolean isDedicated, UInt32 appId)
   at Phoenix.SEWorkshopTool.SpaceGame.SetupBasicGameInfo()
   at Phoenix.WorkshopTool.GameBase.InitSandbox(String instancepath)
   at Phoenix.WorkshopTool.GameBase.InitGame(String[] args)

**Comment by Gwindalmir** [comment]
Sadly, when I released the new update... I forgot to actually test upload.
I noticed it myself yesterday, but solving it will be more involved so it'll take time unfortunately.
Thanks for the report!

**Comment by JamieH** [comment]
https://github.com/Gwindalmir/SEWorkshopTool/blob/350089d5ee5ca79eb9b79c48aa0286fb1c699da3/WorkshopToolCommon/GameBase.cs#L368

You don't check if this is null.

![image](https://user-images.githubusercontent.com/1857320/43867191-36555192-9b60-11e8-9ebd-4e923c09d856.png)

**Comment by Gwindalmir** [comment]
Fixed with #14
