### ISSUE TITLE
Uploads empty mod.

### ISSUE THREAD

**Issue by lizelive** [Gwindalmir/SEWorkshopTool#22]
PS D:\SteamLibrary\steamapps\common\SpaceEngineers> SEWorkshopTool --upload --mods C:\Users\prosa\AppData\Roaming\SpaceEngineers\Mods\RoverRespawn
2019-11-14 19:49:42.775: App Version: 01_193_022
2019-11-14 19:49:42.776: Is official: True [NO][NIS][NAMP]
2019-11-14 19:49:42.776: Environment.ProcessorCount: 8
2019-11-14 19:49:42.820: Environment.OSVersion: Microsoft Windows 10 Education (Microsoft Windows NT 6.2.9200.0)
2019-11-14 19:49:42.820: Environment.CommandLine: "C:\opt\SEWorkshopTool.exe" --upload --mods C:\Users\prosa\AppData\Roaming\SpaceEngineers\Mods\RoverRespawn
2019-11-14 19:49:42.822: Environment.Is64BitProcess: True
2019-11-14 19:49:42.823: Environment.Is64BitOperatingSystem: True
2019-11-14 19:49:42.824: Environment.Version: .NET Framework 4.8.4018.0
2019-11-14 19:49:42.824: Environment.CurrentDirectory: D:\SteamLibrary\steamapps\common\SpaceEngineers
2019-11-14 19:49:42.829: CPU Info: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Setting breakpad minidump AppID = 244850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198049291006 [API loaded no]
2019-11-14 19:49:44.503: SEWT 0.7.1.37086
2019-11-14 19:49:44.526:
2019-11-14 19:49:44.528: Beginning batch workshop upload...
2019-11-14 19:49:44.528:
2019-11-14 19:49:46.175: Processing Mod: JoeTheAntiPro's WeeWooWagon Respawn Rover Mod
2019-11-14 19:49:46.185: Updating Mod: 1912996369; JoeTheAntiPro's WeeWooWagon Respawn Rover Mod
2019-11-14 19:49:52.781: Visibility: Private
2019-11-14 19:49:52.782: Tags:
2019-11-14 19:49:52.784: DLC requirements: None
2019-11-14 19:49:52.786: Dependencies: None
2019-11-14 19:49:52.788: Thumbnail: No change
2019-11-14 19:49:52.803: An exception occurred: Object reference not set to an instance of an object.
2019-11-14 19:49:52.803:    at Phoenix.WorkshopTool.Uploader.Publish()
   at Phoenix.WorkshopTool.GameBase.ProcessItemsUpload(WorkshopType type, List`1 paths, Options options)
   at Phoenix.WorkshopTool.GameBase.<>c__DisplayClass19_0.<UploadMods>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by lizelive** [comment]
That error only happens the second time i try uploading it. The first time it works.

`PS D:\SteamLibrary\steamapps\common\SpaceEngineers> SEWorkshopTool --upload --mods C:\Users\prosa\AppData\Roaming\SpaceEngineers\Mods\RoverRespawn --visibility public
2019-11-14 20:05:24.291: App Version: 01_193_022
2019-11-14 20:05:24.291: Is official: True [NO][NIS][NAMP]
2019-11-14 20:05:24.293: Environment.ProcessorCount: 8
2019-11-14 20:05:24.336: Environment.OSVersion: Microsoft Windows 10 Education (Microsoft Windows NT 6.2.9200.0)
2019-11-14 20:05:24.337: Environment.CommandLine: "C:\opt\SEWorkshopTool.exe" --upload --mods C:\Users\prosa\AppData\Roaming\SpaceEngineers\Mods\RoverRespawn --visibility public
2019-11-14 20:05:24.339: Environment.Is64BitProcess: True
2019-11-14 20:05:24.342: Environment.Is64BitOperatingSystem: True
2019-11-14 20:05:24.343: Environment.Version: .NET Framework 4.8.4018.0
2019-11-14 20:05:24.344: Environment.CurrentDirectory: D:\SteamLibrary\steamapps\common\SpaceEngineers
2019-11-14 20:05:24.350: CPU Info: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Setting breakpad minidump AppID = 244850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198049291006 [API loaded no]
2019-11-14 20:05:26.158: SEWT 0.7.1.37086
2019-11-14 20:05:26.189:
2019-11-14 20:05:26.190: Beginning batch workshop upload...
2019-11-14 20:05:26.191:
2019-11-14 20:05:27.846: Processing Mod: RoverRespawn
2019-11-14 20:05:27.855: Uploading new Mod: RoverRespawn
2019-11-14 20:05:28.350: Removing invalid tags:
2019-11-14 20:05:28.351: Visibility: Public
2019-11-14 20:05:28.352: Tags: Mod
2019-11-14 20:05:28.356: DLC requirements: None
2019-11-14 20:05:28.357: Dependencies: None
2019-11-14 20:05:28.357: Thumbnail: No change
2019-11-14 20:05:31.098: Upload/Publish success: 1913007974
2019-11-14 20:05:31.107: Create modinfo.sbmi success: 1913007974
2019-11-14 20:05:31.107: Complete: RoverRespawn
2019-11-14 20:05:31.108:`

**Comment by Gwindalmir** [comment]
Have you tried without specifying the full path to the mod?

IOW, just try with the mod name:
`SEWorkshopTool --upload --mods RoverRespawn --visibility public`
If you need to specify the full path, try with the --appdata argument:
`SEWorkshopTool --upload --mods RoverRespawn --visibility public --appdata C:\Users\prosa\AppData\Roaming\SpaceEngineers`

**Comment by lizelive** [comment]
Still creates empty mod :(

**Comment by Gwindalmir** [comment]
I'm going to need some more information.
Is this an existing mod you are updating?
If so, when was the last time you successfully updated it, both with and without SEWT?
Does the machine have the full Steam client installed, or only steamcmd.exe?
Does your mod root folder contain both metadata.mod and modinfo.sbmi?
Where is SEWorkshopTool.exe installed? You appear to be running it under your root game installation folder, but it appears to be installed under c:\opt. It should be under Bin64, it's untested in any other configuration.

Can you send me the entire mod folder, including those above mentioned files?
If you'd like to send it privately, you can DM on Discord: Gwindalmir#4453.

**Comment by Gwindalmir** [comment]
I'm closing this due to inactivity.
