### ISSUE TITLE
Exception occurred when uploading script

### ISSUE THREAD

**Issue by ksqk34** [Gwindalmir/SEWorkshopTool#28]
I updated SEWT - created a new exe with the .DLL references which compiled fine.
However when trying to update my script, I now get this error:
![image](https://user-images.githubusercontent.com/44359621/100354403-0ce22f00-2fe8-11eb-9724-7ca82065cc90.png)

The log file mentioned looks like this:

```

2020-11-26 13:03:16.776 - Thread:   1 ->  Log Started
2020-11-26 13:03:16.776 - Thread:   1 ->  Timezone (local - UTC): 0h
2020-11-26 13:03:16.776 - Thread:   1 ->  App Version: 01_197_064
2020-11-26 13:03:16.798 - Thread:   1 ->  Is official: True [NO][IS][NAMP]
2020-11-26 13:03:16.799 - Thread:   1 ->  Branch / Sandbox: SVN
2020-11-26 13:03:16.799 - Thread:   1 ->  Environment.ProcessorCount: 8
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.OSVersion: Microsoft Windows 10 Pro (Microsoft Windows NT 6.2.9200.0)
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.CommandLine: SEWorkshopTool  --upload --scripts "Spug's Easy Auto-Docking 2"
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.Is64BitProcess: True
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.Is64BitOperatingSystem: True
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.Version: .NET Framework 4.8.4250.0
2020-11-26 13:03:16.839 - Thread:   1 ->  Environment.CurrentDirectory: D:\Program Files\Steam\steamapps\common\SpaceEngineers
2020-11-26 13:03:16.846 - Thread:   1 ->  CPU Info: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
2020-11-26 13:03:16.847 - Thread:   1 ->  IntPtr.Size: 8
2020-11-26 13:03:16.847 - Thread:   1 ->  Default Culture: 
2020-11-26 13:03:16.847 - Thread:   1 ->  Default UI Culture: 
2020-11-26 13:03:16.850 - Thread:   1 ->  MyConfig.Load() - START
2020-11-26 13:03:16.854 - Thread:   1 ->     Path: C:\Users\spugy\AppData\Roaming\SpaceEngineers\SpaceEngineersModTool.cfg
2020-11-26 13:03:16.855 - Thread:   1 ->     Config file not found! C:\Users\spugy\AppData\Roaming\SpaceEngineers\SpaceEngineersModTool.cfg
2020-11-26 13:03:16.856 - Thread:   1 ->     NewNewGameScreen: False
2020-11-26 13:03:16.857 - Thread:   1 ->  MyConfig.Load() - END
2020-11-26 13:03:16.874 - Thread:   1 ->  Checksum file is missing, game will run as usual but file integrity won't be verified
2020-11-26 13:03:17.099 - Thread:   1 ->  MyScreenManager()
2020-11-26 13:03:17.164 - Thread:   1 ->  MySandboxGame.Constructor() - START
2020-11-26 13:03:17.164 - Thread:   1 ->     Game dir: D:\Program Files\Steam\steamapps\common\SpaceEngineers\Bin64
2020-11-26 13:03:17.164 - Thread:   1 ->     Content dir: D:\Program Files\Steam\steamapps\common\SpaceEngineers\Content
2020-11-26 13:03:18.383 - Thread:   1 ->     Preallocate - START
2020-11-26 13:03:18.386 - Thread:   1 ->        MySpaceWorldGenerator - START
2020-11-26 13:03:18.389 - Thread:   1 ->        MySpaceWorldGenerator - END
2020-11-26 13:03:18.389 - Thread:   1 ->        MySpaceBuildComponent - START
2020-11-26 13:03:18.389 - Thread:   1 ->        MySpaceBuildComponent - END
2020-11-26 13:03:18.389 - Thread:   1 ->        MyEntities - START
2020-11-26 13:03:18.410 - Thread:   1 ->        MyEntities - END
2020-11-26 13:03:18.410 - Thread:   1 ->        MyObjectBuilder_Base - START
2020-11-26 13:03:18.410 - Thread:   1 ->        MyObjectBuilder_Base - END
2020-11-26 13:03:18.410 - Thread:   1 ->        MyTransparentGeometry - START
2020-11-26 13:03:18.410 - Thread:   1 ->        MyTransparentGeometry - END
2020-11-26 13:03:18.410 - Thread:   1 ->        MyCubeGridDeformationTables - START
2020-11-26 13:03:18.417 - Thread:   1 ->        MyCubeGridDeformationTables - END
2020-11-26 13:03:18.417 - Thread:   1 ->        MyMath - START
2020-11-26 13:03:18.417 - Thread:   1 ->        MyMath - END
2020-11-26 13:03:18.417 - Thread:   1 ->        MySimpleObjectDraw - START
2020-11-26 13:03:18.417 - Thread:   1 ->        MySimpleObjectDraw - END
2020-11-26 13:03:18.433 - Thread:   1 ->        MyEntityComponentsDebugDraw - START
2020-11-26 13:03:18.433 - Thread:   1 ->        MyEntityComponentsDebugDraw - END
2020-11-26 13:03:18.433 - Thread:   1 ->        MyGuiIngameScriptsPage - START
2020-11-26 13:03:18.514 - Thread:   1 ->        MyGuiIngameScriptsPage - END
2020-11-26 13:03:18.514 - Thread:   1 ->        MyGuiScreenAdminMenu - START
2020-11-26 13:03:18.514 - Thread:   1 ->        MyGuiScreenAdminMenu - END
2020-11-26 13:03:18.514 - Thread:   1 ->        MySyncDestructions - START
2020-11-26 13:03:18.514 - Thread:   1 ->        MySyncDestructions - END
2020-11-26 13:03:18.514 - Thread:   1 ->        MySyncEntity - START
2020-11-26 13:03:18.514 - Thread:   1 ->        MySyncEntity - END
2020-11-26 13:03:18.514 - Thread:   1 ->        MyCommandCharacter - START
2020-11-26 13:03:18.517 - Thread:   1 ->        MyCommandCharacter - END
2020-11-26 13:03:18.517 - Thread:   1 ->        MyCommandConsole - START
2020-11-26 13:03:18.519 - Thread:   1 ->        MyCommandConsole - END
2020-11-26 13:03:18.519 - Thread:   1 ->        MyCommandEntity - START
2020-11-26 13:03:18.521 - Thread:   1 ->        MyCommandEntity - END
2020-11-26 13:03:18.521 - Thread:   1 ->        MyAiTargetManager - START
2020-11-26 13:03:18.521 - Thread:   1 ->        MyAiTargetManager - END
2020-11-26 13:03:18.521 - Thread:   1 ->        MyClientDebugCommands - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyClientDebugCommands - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyDedicatedServer - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyDedicatedServer - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyDedicatedServerBase - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyDedicatedServerBase - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerBase - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerBase - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerClient - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerClient - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerClientBase - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerClientBase - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerLobby - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerLobby - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerLobbyClient - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerLobbyClient - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerServerBase - START
2020-11-26 13:03:18.522 - Thread:   1 ->        MyMultiplayerServerBase - END
2020-11-26 13:03:18.522 - Thread:   1 ->        MyServerDebugCommands - START
2020-11-26 13:03:18.523 - Thread:   1 ->        MyServerDebugCommands - END
2020-11-26 13:03:18.523 - Thread:   1 ->        MyAIActionsParser - START
2020-11-26 13:03:18.524 - Thread:   1 ->        MyAIActionsParser - END
2020-11-26 13:03:18.524 - Thread:   1 ->        MyCubeGridDefinitions - START
2020-11-26 13:03:18.550 - Thread:   1 ->        MyCubeGridDefinitions - END
2020-11-26 13:03:18.550 - Thread:   1 ->        MyDefinitionManager - START
2020-11-26 13:03:18.557 - Thread:   1 ->        MyDefinitionManager - END
2020-11-26 13:03:18.557 - Thread:   1 ->     Preallocate - END
2020-11-26 13:03:18.558 - Thread:   1 ->     MyCampaignManager.Constructor() - START
2020-11-26 13:03:18.881 - Thread:   1 ->     MyCampaignManager.Constructor() - END
2020-11-26 13:03:18.881 - Thread:   1 ->  MySandboxGame.Constructor() - END
2020-11-26 13:03:18.901 - Thread:   1 ->  SEWT 0.7.7.23307
2020-11-26 13:03:18.901 - Thread:   1 ->  Log file: C:\Users\spugy\AppData\Roaming\SpaceEngineers\SpaceEngineersModTool_20201126_130316773.log
2020-11-26 13:03:18.923 - Thread:   1 ->  
2020-11-26 13:03:18.924 - Thread:   5 ->  Beginning batch workshop upload...
2020-11-26 13:03:18.924 - Thread:   5 ->  
2020-11-26 13:03:18.936 - Thread:   5 ->  MyWorkshop.GetItemsBlocking: getting 1 items
2020-11-26 13:03:18.938 - Thread:   5 ->  Processing IngameScript: Spug's Easy Auto-Docking 2
2020-11-26 13:03:18.943 - Thread:   5 ->  Updating IngameScript: 2146371052; Spug's Easy Auto-Docking 2
2020-11-26 13:03:18.949 - Thread:   5 ->  MyWorkshop.GetItemsBlocking: getting 1 items
2020-11-26 13:03:18.954 - Thread:   5 ->  Removing invalid tags: 
2020-11-26 13:03:18.956 - Thread:   5 ->  Visibility: 
2020-11-26 13:03:18.956 - Thread:   5 ->  Tags: IngameScript
2020-11-26 13:03:18.956 - Thread:   5 ->  DLC requirements: None
2020-11-26 13:03:18.956 - Thread:   5 ->  Dependencies: None
2020-11-26 13:03:18.956 - Thread:   5 ->  Thumbnail: No change
2020-11-26 13:03:18.959 - Thread:   5 ->  PublishItemBlocking - START
2020-11-26 13:03:18.960 - Thread:   1 ->  ERROR: An exception occurred: Object reference not set to an instance of an object.
2020-11-26 13:03:18.963 - Thread:   1 ->     at Phoenix.WorkshopTool.Uploader.Publish()
   at Phoenix.WorkshopTool.GameBase.ProcessItemsUpload(WorkshopType type, List`1 paths, Options options)
   at Phoenix.WorkshopTool.GameBase.<>c__DisplayClass23_0.<UploadMods>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2020-11-26 13:03:18.963 - Thread:   1 ->  Check the log file above for error details.
2020-11-26 13:03:18.963 - Thread:   1 ->  Steam closed
2020-11-26 13:03:18.963 - Thread:   1 ->  Object reference not set to an instance of an object.
2020-11-26 13:03:18.964 - Thread:   1 ->     at Sandbox.MySandboxGame.Dispose()
   at Phoenix.WorkshopTool.GameBase.CleanupSandbox()

```

What can I do to fix this to get my script back up and running again?
Thanks,
Spug

**Comment by ksqk34** [comment]
Closed since I found your post about this issue and it solved it!
Thanks for the great tool

**Comment by amahlaka** [comment]
@ksqk34  Im having this same issue now, would you mind linking the post that solved it for you?
