### ISSUE TITLE
Unable to upload a Mod to Space engineers workshop

### ISSUE THREAD

**Issue by ARTIcode13** [Gwindalmir/SEWorkshopTool#31]
when trying to upload a mod with the tool, i get an exception:
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=SEWorkshopTool
  Arborescence des appels de procédure :
   at Phoenix.WorkshopTool.Uploader.Phoenix.WorkshopTool.IMod.get_ModId() in E:\projects\perso\games\SEWorkshopTool\WorkshopToolCommon\Uploader.cs:line 58
   at Phoenix.WorkshopTool.Uploader.Publish() in E:\projects\perso\games\SEWorkshopTool\WorkshopToolCommon\Uploader.cs:line 436
   at Phoenix.WorkshopTool.GameBase.ProcessItemsUpload(WorkshopType type, List`1 paths, Options options) in E:\projects\perso\games\SEWorkshopTool\WorkshopToolCommon\GameBase.cs:line 610
   at Phoenix.WorkshopTool.GameBase.<>c__DisplayClass25_0.<UploadMods>b__0() in E:\projects\perso\games\SEWorkshopTool\WorkshopToolCommon\GameBase.cs:line 489
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Seems like the tool is not able to get a valid mod Id to use for upload.

**Comment by Gwindalmir** [comment]
That doesn't look like a release I built. Did you build from source?
What is the command-line you passed?

**Comment by ARTIcode13** [comment]
Hello,

Yes I got same problem with the release that I downloaded from github, so I built the source to get more information.
the command I used is this (publishing a new mod):
.\SEWorkshopTool.exe --upload --mods NewMod --visibility Private --message "Test mod upload with workshopTool"

Thanks

**Comment by ARTIcode13** [comment]
After the changes you commited I get this message : "Upload/Publish FAILED!"
PublishSuccess is equal to true
but the modId is not updating and the Ids array length is still equal to 0

**Comment by Gwindalmir** [comment]
> 
> 
> After the changes you commited I get this message : "Upload/Publish FAILED!"
> PublishSuccess is equal to true
> but the modId is not updating and the Ids array length is still equal to 0

Ah, that's a mistake on my part, the returned items are workshop items, not ids. The upload should have still worked.
