### ISSUE TITLE
Unable to upload/update a mod

### ISSUE THREAD

**Issue by amahlaka** [Gwindalmir/SEWorkshopTool#32]
When I attempt to upload my mod, or change the tags of my uploaded mod, I get the following error in the logs:
```
2021-02-14 14:17:15.646 - Thread:   1 ->  Object reference not set to an instance of an object.
2021-02-14 14:17:15.648 - Thread:   1 ->     at Sandbox.MySandboxGame.Dispose()
   at Phoenix.WorkshopTool.GameBase.CleanupSandbox()

```

**Comment by amahlaka** [comment]
Update: after copying the steam_appid.txt from steamapps/common/spaceengineers to the bin64 folder, issue was resolved

**Comment by Gwindalmir** [comment]
For the record, that error is on exit, it's safe to ignore. The game is calling "MyPlugins.Dispose()" which is throwing an exception.
