### ISSUE TITLE
exception 

### ISSUE THREAD

**Issue by foogs** [Gwindalmir/SEWorkshopTool#33]
2021-02-14 21:21:13.444 - Thread:   6 ->  Processing Mod: NebulaModpackGarage
2021-02-14 21:21:13.447 - Thread:   6 ->  Compiling...
2021-02-14 21:21:13.453 - Thread:   1 ->  ERROR: An exception occurred: Object reference not set to an instance of an object.
2021-02-14 21:21:13.455 - Thread:   1 ->     at Sandbox.Game.World.MyScriptManager.GetAssemblyName(MyModContext mod, String scriptDir)
   at Sandbox.Game.World.MyScriptManager.LoadScripts(String path, MyModContext mod)
   at Phoenix.WorkshopTool.Uploader.Compile()
   at Phoenix.WorkshopTool.GameBase.ProcessItemsUpload(WorkshopType type, List`1 paths, Options options)
   at Phoenix.WorkshopTool.GameBase.<>c__DisplayClass25_0.<UploadMods>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2021-02-14 21:21:13.455 - Thread:   1 ->  Check the log file above for error details.
2021-02-14 21:21:13.456 - Thread:   1 ->  Steam closed
2021-02-14 21:21:13.724 - Thread:   1 ->  Object reference not set to an instance of an object.
2021-02-14 21:21:13.724 - Thread:   1 ->     at Sandbox.MySandboxGame.Dispose()
   at Phoenix.WorkshopTool.GameBase.CleanupSandbox()

**Comment by Gwindalmir** [comment]
Can you post the entire log file?

**Comment by Gwindalmir** [comment]
Looks like it's some regression in the game.
I only triggers on some mods, but not others, and I don't know why.
